name: Digester

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: digester-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1
  OTP_VERSION: 26.0.1
  ELIXIR_VERSION: 1.15.5
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix deps.get

      - run: mix test